theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

title: Abhin
name: Abhin
description: A summary of my projects and ideas.
url: https://abhin.ca

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap

whitelist:
  - jekyll-redirect-from

collections:
  authors:
    output: true

author:
  name: Abhin Chhabra
  avatar: /assets/images/headshot.jpg
  home: /authors/abhin
  bio: Optimization for happiness in progress...
  location: "Toronto, Canada"
  twitter: abhinthere
  linkedin: abhin-chhabra
  instagram: chhabrakadabra
  bitbucket: abhin
  github: chhabrakadabra

twitter:
  username: abhinthere

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true
