theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

title: Abhin
name: Abhin
description: A summary of my projects and ideas.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-remote-theme

whitelist:
  - jekyll-redirect-from

collections:
  authors:
    output: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
