theme: jekyll-theme-merlot

title: Abhin
description: A summary of my projects and ideas.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
  authors:
    output: true
