version: "3.9"
services:
  web:
    image: jekyll/jekyll:latest
    command: jekyll serve --livereload --incremental
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
